[versions]
kotlin = "1.6.10"
androidxlifecycle = "2.4.1"

[libraries]
android-pluginGradle = "com.android.tools.build:gradle:7.1.2"

androidx-core = "androidx.core:core-ktx:1.7.0"
androidx-activity = "androidx.activity:activity-ktx:1.4.0"
androidx-lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "androidxlifecycle" }
androidx-lifecycle-viewmodel-savedstate = { module = "androidx.lifecycle:lifecycle-viewmodel-savedstate", version.ref = "androidxlifecycle" }
androidx-material = "com.google.android.material:material:1.5.0"
androidx-constraintlayout = "androidx.constraintlayout:constraintlayout:2.1.3"

kotlin-pluginGradle = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-stdlib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib", version.ref = "kotlin" }
