[versions]
kotlin = "1.6.10"
coroutines = "1.6.0"
androidxlifecycle = "2.4.1"

[libraries]
android-pluginGradle = "com.android.tools.build:gradle:7.1.2"

androidx-core = "androidx.core:core-ktx:1.7.0"
androidx-activity = "androidx.activity:activity-ktx:1.4.0"
androidx-lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "androidxlifecycle" }
androidx-lifecycle-viewmodel-savedstate = { module = "androidx.lifecycle:lifecycle-viewmodel-savedstate", version.ref = "androidxlifecycle" }
androidx-material = "com.google.android.material:material:1.5.0"
androidx-constraintlayout = "androidx.constraintlayout:constraintlayout:2.1.3"
androidx-security-crypto = "androidx.security:security-crypto:1.0.0"

kotlin-pluginGradle = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-stdlib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib", version.ref = "kotlin" }
kotlin-coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "coroutines" }
kotlin-serialization-json = "org.jetbrains.kotlinx:kotlinx-serialization-json:1.3.2"
kotlin-pluginSerialization = { module = "org.jetbrains.kotlin:kotlin-serialization", version.ref = "kotlin" }
kotlin-datetime = "org.jetbrains.kotlinx:kotlinx-datetime:0.3.2"

okhttp = "com.squareup.okhttp3:okhttp:4.9.3"
retrofit = "com.squareup.retrofit2:retrofit:2.9.0"
retrofit-kotlin-serialization = "com.jakewharton.retrofit:retrofit2-kotlinx-serialization-converter:0.8.0"
jwtdecode = "com.auth0.android:jwtdecode:2.0.1"
